### ISSUE TITLE
Call snippets not working

### ISSUE THREAD

**Issue by oblitum** [xiyaowong/coc-sumneko-lua#1]
I've enabled `enableNvimLuaDev`:

```lua
vim.fn['coc#config']('sumneko-lua', {
    enableNvimLuaDev = true
})
```

~~But while I edit my `init.lua`, even though everything seems to be working, both completion and diagnostics, I'm getting lots of ``"Undefined global `vim`"`` for code with `vim.`. Previously I was using coc-lua with this `lua-dev.nvim` configuration and was not getting this warning:~~

Call snippets, which have been enabled on https://github.com/folke/lua-dev.nvim/commit/a26731909a6790ab80a4c7bc0c25b8d7402c35e9, is not working. It works with the following coc-lua configuration:

```lua
vim.fn['coc#config']('Lua', require('lua-dev').setup{}.settings.Lua)
```

Thanks for the plugin.

**Comment by oblitum** [comment]
Call snippets, which have been enabled on https://github.com/folke/lua-dev.nvim/commit/a26731909a6790ab80a4c7bc0c25b8d7402c35e9, is also not working.

**Comment by oblitum** [comment]
I'm sorry, false alarm, coc-lua was auto installed after removal and I didn't notice, it is what was causing the warning. Now I'm only missing the call snippets.

**Comment by xiyaowong** [comment]
https://github.com/xiyaowong/coc-sumneko-lua/blob/main/settings.md#luacompletioncallsnippet

Don't miss the Settings in the document😃

**Comment by oblitum** [comment]
Oh, nice! I didn't even notice I should have clicked that because it looks like a title for the section down bellow in the README.
