### ISSUE TITLE
g:coc_status is always prefixed with 😺Lua

### ISSUE THREAD

**Issue by antoinemadec** [xiyaowong/coc-sumneko-lua#12]
First, thanks for the amazing plugin.

# Issue
```g:status``` is always prefixed by ```😺Lua```

If I set:
```json
  "Lua.window.statusBar": false,
```

1. ```😺Lua``` does not appear at first when opening a lua file
2. as soon as we jump into another lua file (e.g.: "go definition"), the ```😺Lua``` prefix comes back

I love animals, but I really wanna kill this cat :smile: 

# Expected Behavior
No ```😺Lua``` prefix in ```g:coc_status``` when ``` "Lua.window.statusBar": false,```

# Info
```
coc-sumneko-lua 0.0.12
```
```
vim version: NVIM v0.7.0-dev+809-ge42c90659
node version: v17.2.0
coc.nvim version: 0.0.80-f6a947a8eb
coc.nvim directory: /home/antoine/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-256color
platform: linux
```

**Comment by xiyaowong** [comment]
I think this is sumneko-lua's problem

**Comment by sumneko** [comment]
The cat is so cute, don't hurt it T_T

Please show me the log, see https://github.com/sumneko/lua-language-server/wiki/Default-log-path

**Comment by antoinemadec** [comment]
@sumneko here are the logs: [file_home_antoine_dotfiles.log](https://github.com/xiyaowong/coc-sumneko-lua/files/7820862/file_home_antoine_dotfiles.log)

**Comment by sumneko** [comment]
Can you provide other logs?
I think the client startup 2 server, witch one of them dose not accept your setting.

**Comment by antoinemadec** [comment]
The only other log I have is this one: [service.log](https://github.com/xiyaowong/coc-sumneko-lua/files/7821231/service.log)

**Comment by sumneko** [comment]
I cannot find out what happened from the logs, could you please tell me the filename you jumped to?

**Comment by antoinemadec** [comment]
The file I open first:
```file:///home/antoine/dotfiles/.config/nvim/lua/plugins.lua```
The file I jump to
```file:///home/antoine/dotfiles/.config/nvim/lua/config/lualine.lua```

Even when going back to plugins.lua, the cat is still here.

**Comment by sumneko** [comment]
Is there only one server process(lua-language-server) from beginning to end?
I didn’t find any problems from the logs. Maybe it’s a problem with the client. You can try to log the PRC messages(the client should provide such a debugging function)

**Comment by antoinemadec** [comment]
@sumneko here is a minimal testcase and the PRC messages log you asked for:

# minimal testcase
vimrc
```vim
set rtp+=~/.vim
let g:coc_config_home = '~/toto'
let g:coc_data_home = '~/coc'
let g:coc_global_extensions = ['coc-sumneko-lua']

call plug#begin('./plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

nmap <silent> gd <Plug>(coc-definition)
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
let g:node_client_debug = v:true
```
coc-settings.json
```json
{
	"Lua.window.statusBar": false
}
```

lua/foo.lua:
```lua
require "bar"
```

lua/bar.lua
```empty```

## steps
  1. ```nvim --clean -u vimrc ./lua/foo.lua``` ;  no ```😺Lua``` to be seen
  2. move your cursor to ```bar``` and press ```gd``` to jump
  3. you are in ```bar.lua``` and ```😺Lua``` is back

# logs
All PRC messages: [log.txt](https://github.com/xiyaowong/coc-sumneko-lua/files/7833439/log.txt)

high level log of coc.nvim:
```
2022-01-08T16:14:17.753 INFO (pid:45050) [services] - registered service "sumneko-lua"
2022-01-08T16:14:17.754 INFO (pid:45050) [services] - Sumneko Lua Language Server state change: stopped => starting
2022-01-08T16:14:17.758 INFO (pid:45050) [plugin] - coc.nvim 0.0.80-f6a947a8eb initialized with node: v17.3.0 after 119ms
2022-01-08T16:14:17.764 INFO (pid:45050) [language-client-index] - Language server "sumneko-lua" started with 45061
2022-01-08T16:14:17.888 INFO (pid:45050) [services] - Sumneko Lua Language Server state change: starting => running
2022-01-08T16:14:17.894 INFO (pid:45050) [services] - service sumneko-lua started
2022-01-08T16:14:19.741 INFO (pid:45050) [attach] - receive notification: jumpDefinition []
2022-01-08T16:14:28.233 INFO (pid:45050) [attach] - receive notification: openLog []
```

**Comment by sumneko** [comment]
This log seems dose not what I want.
Please check Is there only one server process(lua-language-server) after your jumping first.
I will add the log into server side next version.

**Comment by antoinemadec** [comment]
> Please check Is there only one server process(lua-language-server) after your jumping first.

Yes, only 1 server, before and after the jump, the PID does not change:
```
   7683 ?        Sl     0:02 /home/antoine/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/lua-language-server -E /home/antoine/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/main.lua --locale=en-us
```

> I will add the log into server side next version.

Got it, let me know when this is pushed.

**Comment by sumneko** [comment]
I just found that the server have supported RPC logs, just add `--rpclog` into the command.

**Comment by antoinemadec** [comment]
@sumneko here is the log with ```--rpclog=true```: [file_home_antoine_toto.log](https://github.com/xiyaowong/coc-sumneko-lua/files/7863039/file_home_antoine_toto.log)

**Comment by xiyaowong** [comment]
I suddenly found this logic problem when checking the code. Sorry for wasting your time @sumneko @antoinemadec
