### ISSUE TITLE
Completion for `require` duplicates the last character

### ISSUE THREAD

**Issue by statiolake** [xiyaowong/coc-sumneko-lua#17]
Thanks for the awesome plugin :)

Please look at next screenshots. Here I want to complete module name `rc.config`. The situation after confirming completion is shown in the next screenshot. As you can see, confirming completion (`coc#_select_confirm()`) adds extra character `g` (the last character of completed module name).

![image](https://user-images.githubusercontent.com/20490597/151693121-ef1018c7-7417-4e04-96b1-75c0dde1135a.png)

![image](https://user-images.githubusercontent.com/20490597/151693123-1867249d-feff-465e-85be-cc6262977ecb.png)

This issue does not appear neither in neovim built-in LSP (with nvim-cmp) nor VSCode, but appears in [coc-lua](https://github.com/josa42/coc-lua) too.

**Comment by xiyaowong** [comment]
You should go to coc.nvim and ask this question
