### ISSUE TITLE
Show loading icon in status bar

### ISSUE THREAD

**Issue by vuleetu** [xiyaowong/coc-sumneko-lua#20]
After installing this coc extension, it doesn't work anyway. There is one loading icon in the status bar. No idea what's wrong.

![image](https://user-images.githubusercontent.com/856776/154473179-74743c32-fefd-4cec-84a0-b7c5c05c89e1.png)

![image](https://user-images.githubusercontent.com/856776/154472914-a46ec78b-6893-4704-a1e3-bcdde1009dee.png)

**Comment by xiyaowong** [comment]
can't reproduce:(

**Comment by vuleetu** [comment]
After deleted .git folder in parent directory, it works like a miracle. @xiyaowong

**Comment by xiyaowong** [comment]
Strange, I haven't encountered this, and it should be a server-side problem @vuleetu
