### ISSUE TITLE
Empty file error

### ISSUE THREAD

**Issue by sabah1994** [xiyaowong/coc-sumneko-lua#24]
Hi, 
When I open an empty lua file before any other files of lua have been opened I get this error

![lua_error](https://user-images.githubusercontent.com/73726199/178506039-ef348c5c-3501-4d17-869a-a71d90a5b564.png)

Note: If I open the same file when another non-empty lua file is already open than it's all good.

**Comment by xiyaowong** [comment]
can't reproduce @sabah1994

**Comment by xiyaowong** [comment]
> Is there a minimum config or set of questions I can answer to help reproduce

No. And I don't think it's the problem of coc or coc-sumneko-lua. @sabah1994
