### ISSUE TITLE
Incorrect generated type for vim.fn.expand()

### ISSUE THREAD

**Issue by lf-** [xiyaowong/coc-sumneko-lua#25]
`expand()` has the signature `expand({string} [, {nosuf} [, {list}]])`, where `list` is a boolean representing whether the output should be a list. Currently it seems that the type generator operates based on parameter names, and assumes this `list` parameter is of type list, which is incorrect.

The generator doesn't currently support manual overrides, which I think this would probably need.

generated definition:

```lua
--- @param list any[]
function vim.fn.expand(expr, nosuf, list) end
```

**Comment by xiyaowong** [comment]
Function signature actually does not have much impact on the use, most people will read the documentation to get the meaning of the parameters. Avoiding these problems is a lot of work, and I don't really want to spend time modifying the data, so, pr welcome:)
