### ISSUE TITLE
Incorrect signature for vim.fn.systemlist

### ISSUE THREAD

**Issue by lf-** [xiyaowong/coc-sumneko-lua#26]
It seems that `builtin-docs.json` has somehow got the wrong signature in it for systemlist():
```json
    "systemlist": [
      "{cmd} [, {input}]",
      "List"
    ],
```

It should have a third parameter `keepempty` per the help page:
```
systemlist({cmd} [, {input} [, {keepempty}]])		*systemlist()*
```

Generated type:
```lua
--- @return list
function vim.fn.systemlist(cmd, input) end
```

**Comment by xiyaowong** [comment]
https://github.com/xiyaowong/coc-sumneko-lua/issues/25#issuecomment-1187187702
