### ISSUE TITLE
Stuck on "Initializing sumneko-lua"

### ISSUE THREAD

**Issue by shmup** [xiyaowong/coc-sumneko-lua#27]
So I just removed `coc-lua` because I couldn't figure out ignoring globals, and hear good things about `coc-sumneko-lua`. 

Opening a bare minimum `lua` file, though, sumneko-lua never stops initializing.

![image](https://user-images.githubusercontent.com/118710/181877464-aa6cf900-cc86-4710-b7ab-0ec07a53e801.png)

I haven't adjusted any settings yet, my `coc-settings.json` is incredibly minimal and unrelated to lua:

```json
{
  "suggest.autoTrigger": "none",
  "diagnostic.enable": true,
  "python.pythonPath": "/usr/bin/python"
}
```

So, curious, anything I should be configuring here? Could you point me to the relevant bits of any documentation, if so?

Cheers

**Comment by xiyaowong** [comment]
![image](https://user-images.githubusercontent.com/47070852/181913704-5734d996-84bb-4b6e-b3d4-7b40c99bc5fe.png)
