### ISSUE TITLE
Cannot change server directory before installing Sumneko Lua

### ISSUE THREAD

**Issue by UrNightmaree** [xiyaowong/coc-sumneko-lua#29]
Hello, so I have a problem with changing server directory. I can't use `sumneko-lua.serverDir` before installing Sumneko Lua.

Here's the output:
```
[coc.nvim] Error on notification "runCommand": Command: sumneko-lua.serverDir
not found
Press ENTER or type command to continue
```

**Comment by xiyaowong** [comment]
`sumneko-lua.serverDir` is not a command. Please check readme carefully
