### ISSUE TITLE
'end' expected cause by "&" symbol, but not error actually

### ISSUE THREAD

**Issue by linkliu** [xiyaowong/coc-sumneko-lua#42]
I got this error when i used to excuted the and operations by "&".
sumneko given the error "'end' expected (to close 'function') near '&' ". like the pic blow.
![image](https://github.com/xiyaowong/coc-sumneko-lua/assets/5306029/118731c1-858c-4150-8ab7-0ae6b573c0c8).
but this not a error actually.

**Comment by linkliu** [comment]
platform:
-windows 11
-gvim 9.0

**Comment by xiyaowong** [comment]
Don't know what's going on, but everything is working fine on my end. It could be that the error wasn't refreshed in time (unlikely). You can also port this issue to [lua-ls](https://github.com/LuaLS/lua-language-server) cc @sumneko

**Comment by sumneko** [comment]
这个错误消息不是lua-ls的，检查你的其他插件

**Comment by linkliu** [comment]
好的，我检查一下其他插件，非常抱歉这么晚才想起来回复
