### ISSUE TITLE
I get LuaParenErrors in documentation.

### ISSUE THREAD

**Issue by SeniorMars** [xiyaowong/coc-sumneko-lua#81]
The best way to show this is through a screenshot:

<img width="1510" alt="image" src="https://github.com/xiyaowong/coc-sumneko-lua/assets/31679231/2fd6d4e1-0a12-47eb-938e-2ea1b3d4b28d">

Here when I use :inspect i see

<img width="1510" alt="image" src="https://github.com/xiyaowong/coc-sumneko-lua/assets/31679231/10860716-b2ef-4e63-a27d-76241bf14995">

I don't know how to fix this, so any help would be appreciated.

**Comment by xiyaowong** [comment]
Is it just the highlighting that's wrong? This should be an issue with coc.nvim. The plugin doesn't handle this part.

**Comment by xiyaowong** [comment]
Alternatively, if you're using certain highlighting plugins, they might also cause this issue. Please try disabling some plugins.
