### ISSUE TITLE
Not completing on backspace

### ISSUE THREAD

**Issue by oblitum** [xiyaowong/coc-sumneko-lua#9]
Maybe this is similar solved as in (I have no idea same solution can help, but the issue is the same):

- https://gitter.im/neoclide/coc.nvim?at=61511336fd7409696e32bf2f
- https://github.com/clangd/coc-clangd/commit/c7994f8c4556ecdebfa878a3b27b29d9a76db7fe#diff-25dfa32302891af3f99f3d635c5edf895541cbcc8dffd67807e8312e445865e1L82-L83

**Comment by oblitum** [comment]
No completion on backspace seems not working in general anymore, it isn't working in coc-clangd/coc-rust-analyzer.

cc @fannheyward (is it working for you at all in any of these languages/extensions?)

**Comment by fannheyward** [comment]
@oblitum yes, completion on backspace is broken with clangd/rust-analyzer, have no idea when/what change made this happen. Will dig into this.

**Comment by oblitum** [comment]
@fannheyward probably intentional? -> https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources/_compare/bd1e8e3%5E...bd1e8e3 (cc @chemzqm).

**Comment by chemzqm** [comment]
It's not supported any more
